---
ID: "d899ed47-4340-45a1-8161-bc97f4ab2097"
Parent: "3e5015d6-042c-49f3-8c46-6c2103cf7885"
Template: "ec428f24-9c5b-4079-b29b-d7f51a850f6f"
Path: /sitecore/client/Applications/FormsBuilder/Components/Layouts/PropertyGridForm/PageSettings/Settings/ReCaptcha Enterprise/Details/ReCaptchaConfiguration
DB: core
SharedFields:
- ID: "0b6b2d34-5308-4aa8-b59d-85ba47e8b8aa"
  Hint: ValueFieldName
  Value: Value
- ID: "0cc7f24b-2013-46c6-8ae3-5233d094ff7c"
  Hint: StaticData
  Value: "{D4646644-0967-4202-9973-BC9F2F5B5185}"
- ID: "3e079fc3-6b2d-41c9-9204-374a786fc761"
  Hint: BindingConfiguration
  Value: recaptchaModeInvisible=SelectedValue
- ID: "a176e7b0-1c0b-4f2e-a494-2df342a75c0e"
  Hint: IsLabelOnTop
  Type: Checkbox
  Value: 1
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T112206Z
    - ID: "3885a716-2eed-47ae-9132-32225f0458ff"
      Hint: FormLabel
      Value: Recaptcha Mode
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "852c3734-c841-47d9-995d-79ef38bb33d7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220614T213720Z
